server:
  port: 8080

spring:
  # kafka配置
  kafka:
    producer:
      bootstrap-servers: 39.106.120.32:9092 #生产消息的接受服务器ip+端口
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 39.106.120.32:9092 #消费消息的获取服务器ip+端口
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/automatic_clock_in_xust #服务器ip mysql端口
    username: root
    password: Chh980929

# mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true